enum ACTION {
  GET_TOKEN_LOG = "GET_TOKEN_LOG",
  SET_TOKEN_LOG = "SET_TOKEN_LOG",
  GET_TOKEN_REG = "GET_TOKEN_REG",
  SET_TOKEN_REG = "SET_TOKEN_REG",

  RECOVER_PASS = "RECOVER_PASS",
  SEND_RECOVERY_CODE = "SEND_RECOVERY_CODE",
  CHECK_RECOVERY_CODE = "CHECK_RECOVERY_CODE",
  SET_NEW_PASS = "SET_NEW_PASS",

  GET_USER_TABLE = "GET_USER_TABLE",
  SET_USER_TABLE = "SET_USER_TABLE",

  SET_MONTH = "SET_MONTH",

  CREATE_NEW_WORKER = "CREATE_NEW_WORKER",
  DELETE_WORKER = "DELETE_WORKER",
  GIVE_VACATION = "GIVE_VACATION",

  SHOW_ALERT = "SHOW_ALERT",
  HIDE_ALERT = "HIDE_ALERT",

  DELETE_NOTIFICATION = "DELETE_NOTIFICATION",

  UPDATE_GAP = "UPDATE_GAP",
}

export default ACTION;
